title: blog.roblesch
author: Christian Robles
email: roblesch@usc.edu
description: 
domain: blog.roblesch.page
url: https://blog.roblesch.page
baseurl:
github_username: roblesch
linkedin_username: roblesch
theme: minima
markdown: kramdown
kramdown:
  math_engine: katex
plugins:
  - jekyll-feed
  - jekyll-seo-tag
