title: roblesch
author: Christian Robles
email: mail@roblesch.page
domain: blog.roblesch.page
url: https://blog.roblesch.page
github_username: roblesch
linkedin_username: roblesch
theme: minima
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
  math_engine: katex
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
